apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: discord-pc-bot
  annotations:
    run.googleapis.com/ingress: all
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/execution-environment: gen2
        run.googleapis.com/cpu-throttling: "false"
    spec:
      containerConcurrency: 1000
      timeoutSeconds: 300
      containers:
      - image: gcr.io/YOUR_PROJECT_ID/discord-pc-bot
        ports:
        - containerPort: 8080
        env:
        - name: DISCORD_BOT_TOKEN
          value: "YOUR_DISCORD_BOT_TOKEN_HERE"
        - name: GEMINI_API_KEY
          value: "YOUR_GEMINI_API_KEY_HERE"
        - name: PORT
          value: "8080"
        resources:
          limits:
            cpu: "1"
            memory: "1Gi"
          requests:
            cpu: "0.5"
            memory: "512Mi"
